### ISSUE TITLE
Installation Issue with Redmine 3.1.1

### ISSUE THREAD

**Issue by plexa16** [marius-balteanu/redmine_tags#15]
Hello,

i wish to install this very nice plugin in my redmine repository, but it fails. I follow your installation guide and i get no errors in the installation guide.
Here my error after installation!:
>App 5672 stdout: 
App 5672 stdout: 
[ 2015-11-12 08:25:15.8185 5447/7fe42036d700 age/Cor/App/Implementation.cpp:303 ]: Could not spawn process for application /srv/redmine/redmine: An error occured while starting up the preloader.
  Error ID: 44e14a36
  Error details saved to: /tmp/passenger-error-4ol7M8.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

><p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

><ol>
  <li>Is this app supposed to be run as the <code>redmine</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
  <li>Please check whether the correct RVM gemset is being used.</li>
  <li>Sometimes, RVM gemsets may be broken.
      <a href="https://github.com/phusion/passenger/wiki/Resetting-RVM-gemsets">Try resetting them.</a></li>
</ol>

><p>-------- The exception is as follows: -------</p>
Could not find acts-as-taggable-on-3.5.0 in any of the sources (Bundler::GemNotFound)
<pre>  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup&#39;
  /srv/redmine/.rvm/gems/ruby-2.1.4/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `&lt;top (required)&gt;&#39;
  /srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /srv/redmine/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:411:in `activate_gem&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:295:in `block in run_load_path_setup_code&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:416:in `running_bundler&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:294:in `run_load_path_setup_code&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:99:in `preload_app&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:153:in `&lt;module:App&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `&lt;main&gt;&#39;</pre>

>[ 2015-11-12 08:25:15.8533 5447/7fe41b7fe700 age/Cor/Req/CheckoutSession.cpp:252 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 44e14a36. Please see earlier logs for details about the error.

I make <pre class="commands">bundle install</pre> after this error but it not works.

Any idea why i get this error?

Thanks

Plexa16 (Hannes)

**Comment by sdwolf** [comment]
I see you are using passenger as a web server and also you have ruby 2.1.4.
What I suggest is you try with ruby 2.2.3 and puma as your webserver. 
From my experience passenger is a source of many headaches and their performance measures are mostly a publicity stunt.

If you need some documentation on setting puma for production, Heroku has great resources here:
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

Let us know if you still encounter any problems after this.

**Comment by plexa16** [comment]
Hello sdwolf,
thanks for your help. The Plugin is now running, because i have reinstall my rvm and it running correctly. But the next problem is, i can't add any tags in my issue. 
I get this error from my redmine log:
>Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 4
Completed 500 Internal Server Error in 301ms (ActiveRecord: 15.7ms)

>ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 4):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:481:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:470:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


>Started GET "/redmine/issues/34792" for 172.17.37.166 at 2015-11-16 09:07:17 +0100
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"34792"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (5.0ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags.html.erb (3.3ms)
  Rendered issue_relations/_form.html.erb (2.5ms)
  Rendered issues/_relations.html.erb (3.8ms)
  Rendered issues/_action_menu.html.erb (3.0ms)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered issues/_attributes.html.erb (14.8ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags_form.html.erb (2.0ms)
  Rendered issues/_form.html.erb (33.4ms)
  Rendered attachments/_form.html.erb (3.0ms)
  Rendered issues/_edit.html.erb (46.7ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb (0.1ms)
  Rendered issues/_sidebar.html.erb (3.1ms)
  Rendered watchers/_watchers.html.erb (3.5ms)
  Rendered issues/show.html.erb within layouts/base (92.8ms)
Completed 200 OK in 189ms (Views: 108.5ms | ActiveRecord: 13.3ms)

i click to an issue and i add an issue and then i geht this message:
>Internal error

>An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

>If you are the Redmine administrator, check your log files for details about the error.

>Back

Please can you help me again?!

Thanks

Plexa

**Comment by plexa16** [comment]
same error as in issue #16
