### ISSUE TITLE
Mysql2::Error: Unknown column 'taggings_count'

### ISSUE THREAD

**Issue by codyliou** [marius-balteanu/redmine_tags#16]
Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 4
Completed 500 Internal Server Error in 1963ms (ActiveRecord: 268.0ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 4):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:142:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

---

Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [i386-mingw32]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.4
  Filesystem                     
Redmine plugins:
  redmine_contacts               4.0.3
  redmine_issue_badge            0.0.1
  redmine_people                 1.1.0
  redmine_tags                   2.0.1-dev

**Comment by marius-balteanu** [comment]
Hello,

Please follow the below steps:
1. run rake acts_as_taggable_on_engine:install:migrations
2. remove first generated migration from /db/migrate
3. run rake db:migrate
4. restart redmine.

and let know if it works or not.

**Comment by plexa16** [comment]
Hello,
i have the same problem but your steps does not work for me.
in my db file i have one folder the migrate folder and the file schema.rb.
and in the folder migrate i have 5 files. what i must delete exactly now.

Thanks
Plexa

**Comment by yzzy** [comment]
@plexa16 do you have any errors running *rake db:migrate* (step 3)?
Which redmine plugins did you install?

**Comment by plexa16** [comment]
@yzzy i have no errors at step 3 and this redmine_tags plugin is the only one plugin that i installed now on my redmine system
Here my Enviroment
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_tags                   2.0.1-dev

**Comment by plexa16** [comment]
okay after 2 hours of testing it. i have fixed my problem.
The problem is in the databases of tags lost a cloumn with name taggings_count.
@codyliou you must add this column with the arttibute integer and default = 0

**Comment by codyliou** [comment]
OK, i have fixed my problem.
