### ISSUE TITLE
Contribute back to upstream ?

### ISSUE THREAD

**Issue by PowerKiKi** [marius-balteanu/redmine_tags#18]
@marius-balteanu, @sdwolf I see you forked and significantly improved [redminecrm/redmine_tags](https://github.com/redminecrm/redmine_tags), which was itself forked from [ixti/redmine_tags](https://github.com/ixti/redmine_tags). As one of the maintainers of the original project, I was wondering if there would be any interest for you to contribute your patches back to upstream ?

I am specifically interested in the compatibility with Redmine 3. But I am also curious about other improvements you made. IMHO it would benefit end-users if we could join forces because [we lack manpower](https://github.com/ixti/redmine_tags/graphs/contributors), and it would reduce the confusion for end-user when he has to choose one of the many forks.

Assuming you'd be interested I have no doubt @ixti would agree to add you as contributors. Also it would be nice if you could sum up the changes you made/plan to make, so we can be sure that our visions are compatible.

**Comment by marius-balteanu** [comment]
Hi, 

We are totally agree to contribute back to upstream and also with having an "official" version of the plugin. 

@sdwolf will get back this week with the changes and the pull request.

**Comment by PowerKiKi** [comment]
Meanwhile I noticed that there are a few things that seems to have diverged. That could be a conflict of visions and may lead to difficulties to merge. Specifically I am concerned about https://github.com/marius-balteanu/redmine_tags/commit/71c3c057ff8a91bada1dfbbb7e521d1017e23b33 where hardcoded tags and tag limit were introduced. IMHO those are not things we would like to have upstream. But if that's ok for you ignore those changes then I guess we could merge.

@sdwolf would you be able to create individual PRs for each significant patches so they can be reviewed independently ?

**Comment by marius-balteanu** [comment]
That commit is no more available, please take a look on the final version (current master) where there are no tags limit or hardcoded tags (it was just an workaround for our internal needs).

The autocomplete now contains only the tags added to that project.

**Comment by sdwolf** [comment]
I am not really sure how to determine which are the significant patches but here is what I suggest:

1. Rebase with upstream master.
2. Create a pull request with all changes and start commenting on key functionality or regressions.
3. I will write test cases for them and start fixing problems.
4. Integrate with travis to make life a little easier.
5. If the pull request gets to big to handle then I will split it into parts backed up by tests written at step 3.

Also, for testing purposes @PowerKiKi would you agree to integrate with a plugin like https://github.com/ZitecCOM/redmine_testing_gems for rspec and soon to come javascript frontend test support? or would you preffer to make the setup standalone / keep using minitest?

**Comment by ixti** [comment]
@marius-balteanu @sdwolf you have full access to ixti/redmine_tags repo now.

I'm absolutely, 100% would LOVE to have integrations with `redmine_testing_gems`.
Also, just for the record, if you want, I'm pretty fine to transfer redmine_tags under ZitecCOM.

**Comment by PowerKiKi** [comment]
I am glad everyone agree.

@sdwolf I gave a try at merging this fork into upstream and gave up quite quickly due to the amount of huge conflicts and given that my ruby skills are very basics. So if you are able to sort this out, that would really be awesome.

TBH I don't really care about technical choices and implementations. As long as we can merge the projects and release a Redmine 3 compatible version that keep similar features as upstream, I'd say you can use any tool that seems appropriate to you. Travis would definitely be a great addition though.

**Comment by PowerKiKi** [comment]
https://github.com/ixti/redmine_tags/pull/111#event-485372455 was merged upstream, thanks everyone !

May I suggest to retire/deprecate/delete this repository (as you see fit) ? ... or just leave it as is...
