### ISSUE TITLE
CSV export with tags column

### ISSUE THREAD

**Issue by monakov-y** [marius-balteanu/redmine_tags#19]
Hi All!

I have a problem exporting tags to CSV. Tags are exported as string
``` #<ActsAsTaggableOn::Tag::ActiveRecord_Associations_CollectionProxy:0xb4538450> ```

Seems that CSV exporter (in ```app/helpers/queries.rb```, function ```csv_value```) cannot join tags collection and convert it to string. If I call ```value.map{|tag| tag.name}.join(', ')``` tags are exported correctly. But it is an ugly hack, because of explicit check of ```ActiveRecord::Associations::CollectionProxy``` class name:

``` ruby
def csv_value(column, object, value)
    format_object(value, false) do |value|
      case value.class.name
      when 'Float'
        sprintf("%.2f", value).gsub('.', l(:general_csv_decimal_separator))
      when 'IssueRelation'
        value.to_s(object)
      when 'Issue'
        if object.is_a?(TimeEntry)
          "#{value.tracker} ##{value.id}: #{value.subject}"
        else
          value.id
        end
      when 'ActiveRecord::Associations::CollectionProxy'
        value.map{|tag| tag.name}.join(', ')
      else
        value
      end
    end
  end
```

How to fix this behavior without hacks?

PS. I'm embedded software programmer, so RoR is kind of black magic for me.

**Comment by marius-balteanu** [comment]
Hi @monakov-y,

Please add you issue here https://github.com/ixti/redmine_tags. This repo is deprecated. 

Thanks,
Marius
