### ISSUE TITLE
Faill to Tag

### ISSUE THREAD

**Issue by frawg** [marius-balteanu/redmine_tags#3]
Hello Marius,

Whenever I try to submit an issue with tags in Redmine, it states Internal Error has occurred. However, I see the tag being created in the 'tags' table. 'taggings' table is empty. This applies for both sdwolf's master branch and your epic/refactoring branch. I tried using both sdwolf's and n-rodriguez's fix_rails4 redmine_acts_as_taggable_on.

-- edit --
Forgot the mention that the issue actually gets created, just without the tags being attached.

Thanks.

**Comment by marius-balteanu** [comment]
Hello @frawg,

Did you run the db migrations from the readme file?
"Run rake acts_as_taggable_on_engine:install:migrations This will generate some migration files in the redmine /db folder. Remove the ones already migrated and run 'rake db:migrate'. If any of them fail just remove them and re-run 'rake db:migrate'."

If yes, please tell me what is your Redmine version and copy here the error from your log file.

Thanks,
Marius

**Comment by frawg** [comment]
Hello @marius-balteanu,
I did the migration. There was no complaints of failed migration. The error log states Mysql2 error unknown column 'taggings_count' in 'field list' : Update 'tags'  Set 'taggings_count' = COALESCE('taggings_count', 0) + 1 Where 'tags'.'id' = 12)
Seems like migration did not include that column. 
Thanks, 
Frawg.

**Comment by marius-balteanu** [comment]
Now is working? Can I close the issue?

**Comment by frawg** [comment]
Yup. It is fixed by manually creating column 'taggings_count' in table 'tags' with int default value 0.

**Comment by pka23** [comment]
Hi all!
same issue for me in redmine/log/production.log
```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': 
UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1):
```

Table tags in redmine db before:
```
mysql> show columns from tags;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```
execute query
```
ALTER TABLE tags ADD COLUMN taggings_count int(11) DEFAULT 0;
```
and after:
```
mysql> show columns from tags;
+----------------+--------------+------+-----+---------+----------------+
| Field          | Type         | Null | Key | Default | Extra          |
+----------------+--------------+------+-----+---------+----------------+
| id             | int(11)      | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255) | YES  |     | NULL    |                |
| taggings_count | int(11)      | YES  |     | 0       |                |
+----------------+--------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)
```
And now tags starting working!!
tnx!
