### ISSUE TITLE
Tags merging on edit

### ISSUE THREAD

**Issue by frawg** [marius-balteanu/redmine_tags#6]
Hello Marius, 

Just had this issue of existing tags on an issue merging on edit. Not sure if it is fixed with the new version of redmine_tags. Currently using redmine 3.1.0 stable, ruby 2.2.2-p95, rails 4.2.3 and redmine_tags 2.0.1-dev.

Thanks,
Frawg.

**Comment by marius-balteanu** [comment]
Hi,

Thanks, I was able to reproduce also on our instance. We'll check.

**Comment by marius-balteanu** [comment]
Hi @frawg,

Can you check please with the latest version from master? 

The issue was generated by the Rails 4.2 update (details [here](https://github.com/mbleigh/acts-as-taggable-on/wiki/Add-a-tag-field-to-forms-in-Rails--4.2-and-above)).

Marius

**Comment by frawg** [comment]
Hi Marius,

It's great. The tags no longer merges on edit. 

Thanks.

**Comment by marius-balteanu** [comment]
Great.
